wiki/encyclopedia/urls.py
from django.urls import path, re_path
from . import views


app_name="encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path('search', views.search, name="search"),
    path("create", views.new_page, name="create"),
    path("random", views.random_page, name="random"),
    re_path(r"^(?P<title>\w+)/edit$", views.edit_page, name="edit"),
    re_path(r"^(?P<title>\w+)$", views.entry, name="entry"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/forms.py
from email import contentmanager
from django import forms


class NewEntryForm(forms.Form):
    title=forms.CharField(max_length=50)
    content=forms.CharField(widget=forms.Textarea, label="Create New Page")

wiki/encyclopedia/views.py
from django.shortcuts import render
from . import util
from .forms import *
import re
import markdown2
import random
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def markdown_to_html(markdown_content):
    html_content = markdown2.markdown(markdown_content)
    return html_content

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    markdown_content=util.get_entry(title)
    if markdown_content == None:
        return render(request, "encyclopedia/error.html")
    html_content = markdown_to_html(markdown_content)
    return render(request, "encyclopedia/entry.html", {"content":html_content, "title": title})
    

def search(request):
    total_entries=util.list_entries() 
    query = request.GET.get('q') #search_query
    results=[] #search_results
    for entry in total_entries:
        if re.search(query, entry, re.IGNORECASE):
            results.append(entry)
            rg=f"^{query}$"
            raw= r'{}'.format(rg)
            if re.search(raw, entry, re.IGNORECASE):
                content=util.get_entry(entry)
                return render(request, "encyclopedia/entry.html", {"content":content, "title": entry.upper()})
    return render(request, "encyclopedia/search.html", {"results":results, "query":query, "res":len(results)!=0})

def new_page(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            markdown_content = form.cleaned_data["content"]
            if title not in util.list_entries():
                util.save_entry(title, markdown_content)
                return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title':title}))
    return render(request, "encyclopedia/create.html", {
        "form": NewEntryForm()
        })

def edit_page(request, title):
    markdown_content=util.get_entry(title)
    if request.method == "POST":
        new_content = request.POST.get("content")
        util.save_entry(title, new_content)
        return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title': title}))
    return render(request, "encyclopedia/edit.html", {"title":title, "content":markdown_content})

def random_page(request):
    total_entries=util.list_entries()
    total=len(total_entries)
    lucky_num = random.randrange(total)
    title = total_entries[lucky_num]
    return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={'title': title}))

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}
    Create Page
{% endblock %}
{% block body %}
{% if red != True %}
    <h1>Create a New Page</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="submit">
        </div>
    </form>
{% else %}
    <h1> Error </h1>
    <h3>This page already exists.</h3>
{% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}
    Edit Page
{% endblock %}
{% block body %}
    <h1>Edit '{{ title }}' </h1>
    <form action="" method="post">
        {% csrf_token %}
        <textarea type="text" name="content">{{ content }}</textarea>
        <input type="submit">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    {{ content|safe }}

    <div>
        <a href="{{title}}/edit" style="text-align: end;">Edit</a>
    </div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    ERROR
{% endblock %}

{% block body %}
    <h1> PAGE DOES NOT EXIST </h1>
    <p>This page has not yet been made and thus, does not exist. Revisit later</p>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{entry}}">{{entry}}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}"> Random Page </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Results
{% endblock %}

{% block body %}
    <h1>Search Results for '{{ query }}'</h1>
{% if res %}
    <ul>
        {% for result in results %}
            <li><a href="{{result}}">{{ result }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h2>No results found.</h2>
{% endif %}
{% endblock %}